# Generated by Django 4.2 on 2024-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
