# Generated by Django 4.2 on 2024-09-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtchat', '0003_inviteroom_inviteuser_delete_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Accepted'), (-1, 'Rejected')], default=0),
        ),
    ]
