# Generated by Django 4.2 on 2024-10-24 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='nickname',
        ),
    ]
