# Generated by Django 4.2 on 2024-08-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='online',
        ),
        migrations.AddField(
            model_name='appuser',
            name='api42auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
