# Generated by Django 4.2 on 2024-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='api42auth',
            field=models.BooleanField(default=False),
        ),
    ]
