# Generated by Django 4.2 on 2024-08-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appuser_api42auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='online',
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
