# Generated by Django 4.2 on 2024-08-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp_totp', '0003_add_timestamps'),
        ('user', '0002_appuser_api42auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='has_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tf_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_users', to='otp_totp.totpdevice'),
        ),
    ]
