# Generated by Django 4.2 on 2024-08-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_appuser_online_appuser_api42auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
    ]
