# Generated by Django 4.2 on 2024-08-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_appuser_online_appuser_api42auth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
