# Generated by Django 4.2 on 2024-08-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_appuser_online_appuser_api42auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='has_2fa_enabled',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='tf_fk',
        ),
    ]
