# Generated by Django 4.2 on 2024-08-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appuser_is_ai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_ai',
        ),
    ]
