# Generated by Django 4.2 on 2024-09-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('LV', 'Latvian')], default='EN', max_length=2),
        ),
    ]
