# Generated by Django 4.2 on 2024-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_appuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
