# Generated by Django 4.2 on 2024-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_appuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('LV', 'Latvian')], default='EN', max_length=20),
        ),
    ]
