# Generated by Django 4.2 on 2024-09-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_stats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
