# Generated by Django 4.2 on 2024-08-23 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player_1_score',
            new_name='loser',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='player_2_score',
            new_name='match_id',
        ),
        migrations.AddField(
            model_name='match',
            name='can_create_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('tournament', 'match_id')},
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_2',
        ),
    ]
