# Generated by Django 4.2 on 2024-09-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_remove_match_can_create_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
