# Generated by Django 4.2 on 2024-07-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='games_lost',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='games_won',
        ),
    ]
