# Generated by Django 5.0.6 on 2024-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_appuser_last_seen_remove_appuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
