# Generated by Django 5.0.6 on 2024-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appuser_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
