# Generated by Django 5.0.6 on 2024-07-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_appuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
