# Generated by Django 5.0.6 on 2024-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_appuser_avatar_appuser_games_lost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
