# Generated by Django 5.0.7 on 2024-07-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='avatar',
            field=models.FileField(blank=True, default='default/default.jpg', null=True, upload_to='avatars/'),
        ),
    ]
