# Generated by Django 5.0.7 on 2024-07-18 15:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_appuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='score',
        ),
        migrations.AddField(
            model_name='appuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 18, 15, 54, 16, 299829, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='id_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(null=True)),
                ('opponent_score', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_as_opponent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
